In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from DPP_NEW import dataPreprocess

In [8]:
import numpy as np
import pandas as pd
dataset = pd.read_csv('dataset.csv')
X=dataset.iloc[:, 2:12].values
y= dataset.iloc[:, [-1]].values

#encoding for categorical flow of data
from sklearn.preprocessing import LabelEncoder
labelencoder_X1=LabelEncoder()
X[:,1]=labelencoder_X1.fit_transform(X[:,1])
labelencoder_X2=LabelEncoder()
X[:,2]=labelencoder_X2.fit_transform(X[:,2])
y=y.astype(float)


from sklearn.preprocessing import Imputer  #bringing the class
imputer= Imputer(missing_values="NaN", strategy="mean", axis=0)
X[:, 2:13]=imputer.fit_transform(X[:,2:12])

from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray().astype(float)
X=X[:,1:]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X_train= sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test) 

FileNotFoundError: File b'dataset.csv' does not exist

In [2]:
X_train, X_test, y_train, y_test

NameError: name 'X_train' is not defined

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from DPP_NEW import dataPreprocess

In [12]:
#using the preprocessing module
X_train, X_test, y_train, y_test  = dataPreprocess('dataset.csv',
               featureColumns=[2,3,4,5,6,7,8,9,10,11],
               targetColumns=[12],                                  
               scalingColumns=[],
               typeOfScaling='minmax',
               encodingColumns={3:'o', 4:'l'},
               dummyVariableTrapRecovery=True)



{2: 0, 3: 1, 4: 2, 5: 3, 6: 4, 7: 5, 8: 6, 9: 7, 10: 8, 11: 9}
{3: 'o', 4: 'l'}
{2: 0, 3: 1, 4: 2, 5: 3, 6: 4, 7: 5, 8: 6, 9: 7, 10: 8, 11: 9}
{3: 'o', 4: 'l'}
dummy print
dummy print2
dummy print


In [13]:
X_train, X_test, y_train, y_test

(array([[ 1.        ,  0.        ,  0.484     , ...,  1.        ,
          1.        ,  0.38107354],
        [ 1.        ,  0.        ,  0.408     , ...,  0.        ,
          1.        ,  0.84386161],
        [ 1.        ,  0.        ,  0.66      , ...,  1.        ,
          1.        ,  0.45058126],
        ..., 
        [ 0.        ,  1.        ,  0.602     , ...,  1.        ,
          0.        ,  0.78205911],
        [ 0.        ,  1.        ,  0.504     , ...,  1.        ,
          0.        ,  0.15152158],
        [ 1.        ,  0.        ,  0.752     , ...,  0.        ,
          1.        ,  0.14145472]]),
 array([[ 1.        ,  0.        ,  0.618     , ...,  1.        ,
          0.        ,  0.79270195],
        [ 1.        ,  0.        ,  0.444     , ...,  1.        ,
          0.        ,  0.13186684],
        [ 0.        ,  0.        ,  0.926     , ...,  0.        ,
          0.        ,  0.93989267],
        ..., 
        [ 0.        ,  1.        ,  0.602     , ...,

In [14]:
def sigmoidActivation(x):
    return 1 / (1 + np.exp(-x))
    # return expit(x)  
    
def derivative_of_sigmoid(x):
    return x*(1-x)

In [15]:
SynapseMatrix1 = np.random.random((11,6))
SynapseMatrix2 = np.random.random((6,5))
SynapseMatrix3 = np.random.random((5,4))
SynapseMatrix4 = np.random.random((4,1))

In [16]:
for i in np.arange(10000):
    layer0 = X_train
    layer1 = sigmoidActivation(np.dot(layer0, SynapseMatrix1))
    layer2 = sigmoidActivation(np.dot(layer1, SynapseMatrix2))
    layer3 = sigmoidActivation(np.dot(layer2, SynapseMatrix3))
    layer4 = sigmoidActivation(np.dot(layer3, SynapseMatrix4))
    layer4_error = y_train - layer4
    
    if (i% 1000)==0:
        print ("Error: "+str(np.mean(np.abs(layer4_error))))
    
    layer4_delta = layer4_error*derivative_of_sigmoid(layer4)
    
    layer3_error = layer4_delta.dot(SynapseMatrix4.T)
    layer3_delta = layer3_error*derivative_of_sigmoid(layer3)
    
    layer2_error=  layer3_delta.dot(SynapseMatrix3.T)
    layer2_delta = layer2_error*derivative_of_sigmoid(layer2)
    
    layer1_error=  layer2_delta.dot(SynapseMatrix2.T)
    layer1_delta = layer1_error*derivative_of_sigmoid(layer1)
    
      #Update weights
    SynapseMatrix4 = SynapseMatrix4 + layer3.T.dot(layer4_delta)
    SynapseMatrix3 = SynapseMatrix3 + layer2.T.dot(layer3_delta)
    SynapseMatrix2 = SynapseMatrix2 + layer1.T.dot(layer2_delta)
    SynapseMatrix1 = SynapseMatrix1 + layer0.T.dot(layer1_delta)
    
#output after the training
print("Output after training:")
print(layer4)

Error: 0.688131837449


/Users/debajitkumarsandilya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


Error: 0.204444444444
Error: 0.204444444444
Error: 0.204444444444
Error: 0.204444444444
Error: 0.204444444444
Error: 0.204444444444
Error: 0.204444444444
Error: 0.204444444444
Error: 0.204444444444
Output after training:
[[  9.22548508e-273]
 [  6.19208773e-287]
 [  3.06061507e-247]
 ..., 
 [  8.24402215e-203]
 [  3.50784596e-182]
 [  5.83748175e-255]]


In [17]:
layer0 = X_test
layer1 = sigmoidActivation(np.dot(layer0, SynapseMatrix1))
layer2 = sigmoidActivation(np.dot(layer1, SynapseMatrix2))
layer3 = sigmoidActivation(np.dot(layer2, SynapseMatrix3))
layer4 = sigmoidActivation(np.dot(layer3, SynapseMatrix4))
y_pred= layer4

/Users/debajitkumarsandilya/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [18]:
y_pred.astype(float)

array([[  1.08571454e-219],
       [  3.25328093e-229],
       [  5.35502315e-166],
       ..., 
       [  5.50732095e-210],
       [  5.96156817e-265],
       [  1.96570245e-224]])

In [19]:
y_pred=(y_pred>=0.5) 
y_pred.astype(int)
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[1441    0]
 [ 359    0]]


In [20]:
1387+57

1444

In [21]:
accuracy=1444/1800
accuracy

0.8022222222222222

In [22]:
from sklearn.metrics import accuracy_score, classification_report, precision_score, recall_score,f1_score

In [23]:
creport = classification_report(y_true = y_test, y_pred = y_pred)
print(creport)

             precision    recall  f1-score   support

          0       0.80      1.00      0.89      1441
          1       0.00      0.00      0.00       359

avg / total       0.64      0.80      0.71      1800



/Users/debajitkumarsandilya/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
#Judgement
#also stored the code in a separate file(test-code)
dataset_judge= pd.read_csv('judge.csv')

FileNotFoundError: File b'judge.csv' does not exist

In [25]:
X=dataset_judge.iloc[:, 2:12].values

NameError: name 'dataset_judge' is not defined

In [31]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X1=LabelEncoder()
X[:,1]=labelencoder_X1.fit_transform(X[:,1])
labelencoder_X2=LabelEncoder()
X[:,2]=labelencoder_X2.fit_transform(X[:,2])

In [32]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[1])
X=onehotencoder.fit_transform(X).toarray().astype(float)
X=X[:,1:]

In [33]:
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
X= sc_X.fit_transform(X)



In [34]:
layer0 = X
layer1 = sigmoidActivation(np.dot(layer0, SynapseMatrix1))
layer2 = sigmoidActivation(np.dot(layer1, SynapseMatrix2))
layer3 = sigmoidActivation(np.dot(layer2, SynapseMatrix3))
layer4 = sigmoidActivation(np.dot(layer3, SynapseMatrix4))
y_pred = layer4

In [35]:
y_pred

array([[  1.08883192e-235],
       [  1.08883134e-235],
       [  1.08883133e-235],
       [  1.13938878e-094],
       [  1.09314506e-235],
       [  2.37122489e-235],
       [  5.00000000e-001],
       [  4.99999999e-001],
       [  1.08883133e-235],
       [  1.79027635e-232],
       [  4.99999999e-001],
       [  1.08883133e-235],
       [  1.08889749e-235],
       [  1.08883136e-235],
       [  4.99999999e-001],
       [  1.08883580e-235],
       [  1.08964142e-235],
       [  1.08883133e-235],
       [  1.08883133e-235],
       [  1.09116066e-235],
       [  1.08883136e-235],
       [  1.08883580e-235],
       [  1.08927051e-235],
       [  1.08883148e-235],
       [  5.00000000e-001],
       [  1.08883133e-235],
       [  1.08883143e-235],
       [  1.08883133e-235],
       [  1.79027635e-232],
       [  1.08889749e-235],
       [  1.08889749e-235],
       [  1.08883133e-235],
       [  1.08883133e-235],
       [  5.00000000e-001],
       [  1.29341816e-235],
       [  4.99999999

In [36]:
Exited=(y_pred>=0.5).astype(int) 
Exited=Exited.astype(int)
Exited

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [37]:
import csv

In [40]:
CustomerID=dataset_judge.iloc[:, 0].values
CustomerID= CustomerID.reshape((-1, 1)) 
CustomerID

array([[15605215],
       [15567855],
       [15780256],
       [15592229],
       [15788683],
       [15693203],
       [15635125],
       [15582129],
       [15703482],
       [15670738],
       [15624775],
       [15741094],
       [15687828],
       [15661708],
       [15790497],
       [15620103],
       [15586680],
       [15749557],
       [15622443],
       [15745533],
       [15691647],
       [15599289],
       [15766826],
       [15643523],
       [15720637],
       [15693947],
       [15726556],
       [15591257],
       [15792473],
       [15605113],
       [15628904],
       [15586821],
       [15637829],
       [15648075],
       [15654760],
       [15796115],
       [15812918],
       [15595282],
       [15684171],
       [15625761],
       [15632344],
       [15572767],
       [15696301],
       [15682928],
       [15776124],
       [15594685],
       [15688691],
       [15615032],
       [15754820],
       [15799422],
       [15739248],
       [15696637],
       [1569

In [41]:
B=np.concatenate((CustomerID,Exited ), axis=1)

In [42]:
B

array([[15605215,        0],
       [15567855,        0],
       [15780256,        0],
       ..., 
       [15726103,        1],
       [15766374,        0],
       [15684960,        0]])

In [44]:
with open("predict.csv","w+") as my_csv:
    csvWriter = csv.writer(my_csv,delimiter=',')
    csvWriter.writerows(B)